# Generated by Django 3.0.4 on 2020-03-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200317_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pricd',
            new_name='price',
        ),
    ]
