# Generated by Django 3.0.4 on 2020-03-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200317_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='discription',
            new_name='description',
        ),
    ]
